question_data = [
    {
        "category": "Science: Computers",
        "type": "boolean",
        "difficulty": "easy",
        "text": "Linus Torvalds created Linux and Git.",
        "answer": "True",
        "inanswers": ["False"],
    },
    {
        "category": "Science: Computers",
        "type": "boolean",
        "difficulty": "easy",
        "text": "The logo for Snapchat is a Bell.",
        "answer": "False",
        "inanswers": ["True"],
    },
    {
        "category": "Science: Computers",
        "type": "boolean",
        "difficulty": "easy",
        "text": "RAM stands for Random Access Memory.",
        "answer": "True",
        "inanswers": ["False"],
    },
    {
        "category": "Science: Computers",
        "type": "boolean",
        "difficulty": "easy",
        "text": "Ada Lovelace is often considered the first computer programmer.",
        "answer": "True",
        "inanswers": ["False"],
    },
    {
        "category": "Science: Computers",
        "type": "boolean",
        "difficulty": "easy",
        "text": "In most programming languages, the operator ++ is equivalent to the statement &quot;+= 1&quot;.",
        "answer": "True",
        "inanswers": ["False"],
    },
    {
        "category": "Science: Computers",
        "type": "boolean",
        "difficulty": "easy",
        "text": "Time on Computers is measured via the EPOX System.",
        "answer": "False",
        "inanswers": ["True"],
    },
    {
        "category": "Science: Computers",
        "type": "boolean",
        "difficulty": "easy",
        "text": "The Windows 7 operating system has six main editions.",
        "answer": "True",
        "inanswers": ["False"],
    },
    {
        "category": "Science: Computers",
        "type": "boolean",
        "difficulty": "easy",
        "text": "The Windows ME operating system was released in the year 2000.",
        "answer": "True",
        "inanswers": ["False"],
    },
    {
        "category": "Science: Computers",
        "type": "boolean",
        "difficulty": "easy",
        "text": "The NVidia GTX 1080 gets its name because it can only render at a 1920x1080 screen resolution.",
        "answer": "False",
        "inanswers": ["True"],
    },
    {
        "category": "Science: Computers",
        "type": "boolean",
        "difficulty": "easy",
        "text": "Linux was first created as an alternative to Windows XP.",
        "answer": "False",
        "inanswers": ["True"],
    },
]
